<?php

namespace Blutrixx\GeneratorEngine\Tests\Unit\Generators\Frontend;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Regression coverage for the list-feature slot-prop-name contract.
 *
 * Bug: `features/list/component.stub` (List.vue, generated by
 * ListComponentGenerator) wraps <ListTable>, exactly like
 * `features/list/page.stub` (ListPage.vue, generated by ListPageGenerator)
 * does — confirmed against the real, hand-completed reference components
 * SYSTEM_SHELL/FRONTEND/src/pages/modules/core/Locations/LocationTypes/
 * Components/LocationTypesList.vue and .../Access/Permissions/Components/
 * PermissionsList.vue, both of which wrap <ListTable> and destructure every
 * `#cell-*` slot as `{ row }` (ListTable forwards ReportTable's slot props
 * verbatim, and ReportTable.vue emits `<slot :name="`cell-${col.key}`"
 * :row="row" ...>` — it never provides an `item` prop). component.stub used
 * to hard-code `{ item }` for its `#cell-actions` and `#cell-[[primaryKey]]`
 * slots while the `[[customCellRenderers]]` placeholder spliced into the
 * very same file (via BaseComponentGenerator::
 * generateCustomCellRenderersFromListFields()) already hard-coded `{ row }`
 * — an internal, single-file contract break that left every badge/boolean/FK
 * column in a generated List.vue reading `row` while its own actions/primary
 * cell used `item`, which was always undefined.
 *
 * This test reads the raw .stub files directly (the stubs are the source of
 * truth to protect) and asserts every `#cell-*` slot in the list feature
 * templates destructures the same prop name.
 *
 * Originally scoped to just `frontend/features/list/`. Broadened to sweep
 * the whole `src/Generators/Templates/` tree (see the tests below
 * `test_cell_slot_prop_name_is_row_not_item`) after the same bug class was
 * found lurking (already-correct, as it turns out) in
 * `frontend/features/custom/{tab_action,header_modal}.stub` and the unused
 * legacy `frontend/features/delegation/{tab,modal}.stub` — those wrap
 * <ListPageBareTable> instead of <ListTable>, and ListPageBareTable.vue's
 * own cell slots expose `:item="item"`, never `:row`, so `{ item }` is
 * correct there. The generalized test asserts the universal invariant
 * (every #cell-* slot within one file agrees with itself) tree-wide, plus
 * pins the expected name for every stub whose wrapped component is known.
 */
class ListSlotPropConsistencyTest extends TestCase
{
    private function listDir(): string
    {
        return dirname(__DIR__, 4) . '/src/Generators/Templates/frontend/features/list';
    }

    private function readStub(string $filename): string
    {
        $path = $this->listDir() . '/' . $filename;
        $this->assertFileExists($path, "Expected stub file not found: {$path}");

        return (string) file_get_contents($path);
    }

    /**
     * Extract the destructured prop name from every `#cell-*="{ xxx }"`
     * template slot binding found in the given stub content.
     *
     * @return string[]
     */
    private function extractCellSlotPropNames(string $stubContent): array
    {
        preg_match_all('/#cell-[\w\[\]]+="\{\s*(\w+)\s*\}"/', $stubContent, $matches);

        return $matches[1];
    }

    public function test_component_stub_cell_slots_all_use_the_same_prop_name(): void
    {
        $propNames = $this->extractCellSlotPropNames($this->readStub('component.stub'));

        $this->assertNotEmpty($propNames, 'Sanity check: component.stub should declare at least one #cell-* slot.');
        $this->assertCount(
            1,
            array_unique($propNames),
            'component.stub declares #cell-* slots with inconsistent destructured prop names: ['
            . implode(', ', $propNames) . ']. Every #cell-* slot in a single file must agree, since '
            . 'they are all provided by the same wrapping <ListTable>/<ReportTable>.'
        );
    }

    /**
     * page.stub (2026-08-05 redesign) no longer declares any #cell-* slot of
     * its own — it wraps <CrudListPanel> (SYSTEM_SHELL/FRONTEND, hand
     * -maintained, outside this package's Templates/ tree and this test's
     * scope), which owns the #cell-actions binding internally and forwards
     * every other #cell-{key} slot straight through to whatever the caller
     * supplies via [[customCellRenderers]]. There is nothing left in the raw
     * stub file for a "does page.stub agree with component.stub" test to
     * check — that invariant now lives inside CrudListPanel.vue itself.
     */
    public function test_cell_slot_prop_name_is_row_not_item(): void
    {
        // Pinned to the real value (not just "consistent with itself") so a
        // future edit that renames component.stub to `item` still fails
        // loudly — ReportTable.vue, the actual underlying component, only ever
        // binds `:row="row"` on its `cell-*` slots, never `:item`.
        $componentPropNames = array_unique($this->extractCellSlotPropNames($this->readStub('component.stub')));

        $this->assertSame(['row'], array_values($componentPropNames));
    }

    // -------------------------------------------------------------------
    // Whole-tree sweep: every stub anywhere under src/Generators/Templates/
    // must be internally consistent — every #cell-* slot within a single
    // file must destructure the same prop name, whatever that name is.
    // This doesn't assume the name is 'row' tree-wide: stubs that wrap
    // <ListPageBareTable> (features/custom/tab_action.stub,
    // features/custom/header_modal.stub, and the unused legacy
    // features/delegation/{tab,modal}.stub) genuinely use `{ item }`,
    // because ListPageBareTable.vue's own cell slots are
    // `<slot :name="cell-${col.key}" :item="item" ...>` — confirmed in
    // SYSTEM_SHELL/FRONTEND/src/layouts/ListPageBareTable.vue. Only
    // per-file consistency is a universal invariant; the specific name is
    // pinned per-file below for the files whose wrapped component is known.
    // -------------------------------------------------------------------

    private function templatesRoot(): string
    {
        return dirname(__DIR__, 4) . '/src/Generators/Templates';
    }

    /**
     * @return string[] Absolute paths to every file under Templates/.
     */
    private function allTemplateFiles(): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($this->templatesRoot(), \FilesystemIterator::SKIP_DOTS)
        );
        foreach ($iterator as $fileInfo) {
            if ($fileInfo->isFile()) {
                $files[] = $fileInfo->getPathname();
            }
        }
        sort($files);

        return $files;
    }

    public function test_every_template_file_has_internally_consistent_cell_slot_prop_names(): void
    {
        $offenders = [];

        foreach ($this->allTemplateFiles() as $path) {
            $content = (string) file_get_contents($path);
            $propNames = array_unique($this->extractCellSlotPropNames($content));

            if (count($propNames) > 1) {
                $offenders[$path] = $propNames;
            }
        }

        $this->assertSame(
            [],
            $offenders,
            "The following template files mix multiple #cell-* slot prop names within the same file:\n"
            . implode("\n", array_map(
                fn ($path, $names) => " - {$path}: [" . implode(', ', $names) . ']',
                array_keys($offenders),
                array_values($offenders)
            ))
        );
    }

    /**
     * Pin the resolved prop name for every stub whose wrapped component is
     * known, so a regression (e.g. reverting a fix, or introducing a new
     * stub with the wrong name for its wrapped component) fails loudly
     * instead of only tripping the internal-consistency check above.
     *
     * @return array<string, string> relative path (from Templates/) => expected prop name
     */
    public static function knownCellSlotStubProvider(): array
    {
        return [
            // Wraps <ListTable> -> <ReportTable>, which only ever exposes :row="row".
            'frontend/features/list/component.stub wraps ListTable (row)' => ['frontend/features/list/component.stub', 'row'],
            // page.stub (2026-08-05) no longer declares its own #cell-* slots
            // at all -- it wraps <CrudListPanel>, which owns #cell-actions
            // internally (see ListSlotPropConsistencyTest's docblock above
            // test_cell_slot_prop_name_is_row_not_item). Deliberately not
            // listed here any more -- it would fail the "at least one slot"
            // premise this provider's assertion depends on.
            // tab_action.stub is what a delegation/custom-feature TAB actually
            // renders from — DelegationTabComponentGenerator::generateDelegation()
            // hands off to CustomFeatureTabComponentGenerator, which reads this
            // stub. Migrated onto <ListTable>, hence 'row'.
            'frontend/features/custom/tab_action.stub wraps ListTable (row)' => ['frontend/features/custom/tab_action.stub', 'row'],
            // Wrap <ListPageBareTable>, whose own cell slots expose :item="item".
            'frontend/features/custom/header_modal.stub wraps ListPageBareTable (item)' => ['frontend/features/custom/header_modal.stub', 'item'],
            // NOTE: features/delegation/{tab,modal}.stub are NOT read by any
            // generator (verified: zero references outside Templates/). They are
            // dead copies kept in sync with the custom/* stubs by hand. Covered
            // here only so the pair does not drift further while they survive.
            'frontend/features/delegation/tab.stub wraps ListPageBareTable (item)' => ['frontend/features/delegation/tab.stub', 'item'],
            'frontend/features/delegation/modal.stub wraps ListPageBareTable (item)' => ['frontend/features/delegation/modal.stub', 'item'],
        ];
    }

    #[DataProvider('knownCellSlotStubProvider')]
    public function test_known_stub_uses_the_prop_name_its_wrapped_component_actually_exposes(string $relativePath, string $expectedProp): void
    {
        $path = $this->templatesRoot() . '/' . $relativePath;
        $this->assertFileExists($path);

        $propNames = array_unique($this->extractCellSlotPropNames((string) file_get_contents($path)));

        $this->assertSame([$expectedProp], array_values($propNames));
    }
}
