<?php

namespace Blutrixx\GeneratorEngine\Tests\Unit\Generators\Frontend;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Regression coverage for the list-feature slot-prop-name contract.
 *
 * Historical bug (fixed, and the fixed file since deleted as dead code on
 * 2026-08-06): `features/list/component.stub` (List.vue, generated by the
 * now-removed ListComponentGenerator) used to hard-code `{ item }` for its
 * `#cell-actions` and `#cell-[[primaryKey]]` slots while the
 * `[[customCellRenderers]]` placeholder spliced into the very same file
 * already hard-coded `{ row }` — an internal, single-file contract break
 * that left every badge/boolean/FK column reading `row` while its own
 * actions/primary cell used `item`, which was always undefined.
 * ListComponentGenerator, its MobileApp subclass, and both list/component
 * stubs were confirmed to have zero live callers and deleted outright
 * (superseded entirely by page.stub / CrudListPanel.vue), so there is
 * nothing left of that specific file for this test to protect.
 *
 * What remains: a whole-tree sweep (`allTemplateFiles()` below) confirming
 * every `#cell-*` slot within a single template file destructures the same
 * prop name, plus pinned expectations for the stubs whose wrapped component
 * is known — `frontend/features/custom/tab_action.stub` (wraps <ListTable>,
 * hence `row`) and `frontend/features/custom/header_modal.stub` (wraps
 * <ListPageBareTable>, whose own cell slots expose `:item="item"`, hence
 * `item`). The legacy `frontend/features/delegation/{tab,modal}.stub` pair
 * that used to sit alongside them was likewise confirmed dead (zero
 * generator references) and deleted 2026-08-06.
 */
class ListSlotPropConsistencyTest extends TestCase
{
    /**
     * Extract the destructured prop name from every `#cell-*="{ xxx }"`
     * template slot binding found in the given stub content.
     *
     * @return string[]
     */
    private function extractCellSlotPropNames(string $stubContent): array
    {
        preg_match_all('/#cell-[\w\[\]]+="\{\s*(\w+)\s*\}"/', $stubContent, $matches);

        return $matches[1];
    }

    // -------------------------------------------------------------------
    // Whole-tree sweep: every stub anywhere under src/Generators/Templates/
    // must be internally consistent — every #cell-* slot within a single
    // file must destructure the same prop name, whatever that name is.
    // This doesn't assume the name is 'row' tree-wide: stubs that wrap
    // <ListPageBareTable> (features/custom/tab_action.stub,
    // features/custom/header_modal.stub) genuinely use `{ item }`,
    // because ListPageBareTable.vue's own cell slots are
    // `<slot :name="cell-${col.key}" :item="item" ...>` — confirmed in
    // SYSTEM_SHELL/FRONTEND/src/layouts/ListPageBareTable.vue. Only
    // per-file consistency is a universal invariant; the specific name is
    // pinned per-file below for the files whose wrapped component is known.
    // -------------------------------------------------------------------

    private function templatesRoot(): string
    {
        return dirname(__DIR__, 4) . '/src/Generators/Templates';
    }

    /**
     * @return string[] Absolute paths to every file under Templates/.
     */
    private function allTemplateFiles(): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($this->templatesRoot(), \FilesystemIterator::SKIP_DOTS)
        );
        foreach ($iterator as $fileInfo) {
            if ($fileInfo->isFile()) {
                $files[] = $fileInfo->getPathname();
            }
        }
        sort($files);

        return $files;
    }

    public function test_every_template_file_has_internally_consistent_cell_slot_prop_names(): void
    {
        $offenders = [];

        foreach ($this->allTemplateFiles() as $path) {
            $content = (string) file_get_contents($path);
            $propNames = array_unique($this->extractCellSlotPropNames($content));

            if (count($propNames) > 1) {
                $offenders[$path] = $propNames;
            }
        }

        $this->assertSame(
            [],
            $offenders,
            "The following template files mix multiple #cell-* slot prop names within the same file:\n"
            . implode("\n", array_map(
                fn ($path, $names) => " - {$path}: [" . implode(', ', $names) . ']',
                array_keys($offenders),
                array_values($offenders)
            ))
        );
    }

    /**
     * Pin the resolved prop name for every stub whose wrapped component is
     * known, so a regression (e.g. reverting a fix, or introducing a new
     * stub with the wrong name for its wrapped component) fails loudly
     * instead of only tripping the internal-consistency check above.
     *
     * @return array<string, string> relative path (from Templates/) => expected prop name
     */
    public static function knownCellSlotStubProvider(): array
    {
        return [
            // tab_action.stub is what a delegation/custom-feature TAB actually
            // renders from — DelegationTabComponentGenerator::generateDelegation()
            // hands off to CustomFeatureTabComponentGenerator, which reads this
            // stub. Wraps <ListTable>, hence 'row'.
            'frontend/features/custom/tab_action.stub wraps ListTable (row)' => ['frontend/features/custom/tab_action.stub', 'row'],
            // Wraps <ListPageBareTable>, whose own cell slots expose :item="item".
            'frontend/features/custom/header_modal.stub wraps ListPageBareTable (item)' => ['frontend/features/custom/header_modal.stub', 'item'],
        ];
    }

    #[DataProvider('knownCellSlotStubProvider')]
    public function test_known_stub_uses_the_prop_name_its_wrapped_component_actually_exposes(string $relativePath, string $expectedProp): void
    {
        $path = $this->templatesRoot() . '/' . $relativePath;
        $this->assertFileExists($path);

        $propNames = array_unique($this->extractCellSlotPropNames((string) file_get_contents($path)));

        $this->assertSame([$expectedProp], array_values($propNames));
    }
}
