<?php

namespace Blutrixx\GeneratorEngine\Schema;

/**
 * SchemaConventions
 *
 * Single source of truth for this project's audit/system-column convention:
 * every table generated by this engine gets `id`, `uuid`, `created_at`,
 * `updated_at`, `deleted_at`, `created_by_id`, `updated_by_id` automatically
 * (see MigrationGenerator::generateAuditFields() / generateSystemIndexes()
 * and any generated `Migrations/*.php` file for a real example). The
 * project's own hand-authoring workflow instructs schema authors to leave
 * these columns OUT of hand-written SQL entirely — "the generator adds
 * these to every module automatically" — which means the columns are, by
 * design, frequently absent from a table at the moment it is first
 * introspected (a bulk command scaffolding a module for a table that
 * doesn't exist yet, or a hand-authored CREATE TABLE that deliberately
 * omits them).
 *
 * DEFAULT_FLAGS is unconditional — SchemaIntrospector::meta() returns it
 * verbatim for every table, existing or not, with no per-table override and
 * no live-schema check of the real audit columns at all (removed
 * 2026-08-16; see SchemaIntrospector::meta()'s own docblock for why). A
 * table's audit columns are not user-configurable business data any more
 * than they're an option in the module wizard UI — they're what this
 * generator's own migrations always produce, full stop. A real table that
 * doesn't yet match is expected to be brought in line with the convention,
 * not accommodated.
 */
final class SchemaConventions
{
    /**
     * Default value of each derived flag, per this project's convention.
     * Every one is `true` because every generated table gets all four
     * unconditionally (see class docblock).
     */
    public const DEFAULT_FLAGS = [
        'has_timestamps'      => true,
        'has_soft_deletes'    => true,
        'has_uuid'            => true,
        'has_creator_updater' => true,
    ];
}
